<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>example.pde.rcp</groupId>
		<artifactId>example.pde.rcp.parent</artifactId>
		<version>0.7.0-SNAPSHOT</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>example.rcp.tests.report</artifactId>

	<profiles>
		<profile>
			<id>jacoco</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>${jacoco-maven-plugin-version}</version>
						<executions>
							<execution>
								<phase>verify</phase>
								<goals>
									<goal>report-aggregate</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<version>${build-helper-maven-plugin-version}</version>
						<executions>
							<execution>
								<id>copy-jacoco-reports</id>
								<phase>verify</phase>
								<goals>
									<goal>add-resource</goal>
								</goals>
								<configuration>
									<resources>
										<resource>
											<directory>${project.build.directory}</directory>
											<includes>
												<include>**/*</include>
											</includes>
											<!--<targetPath>${basedir}/jacoco-reports</targetPath>-->
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<dependencies>
		<dependency>
			<groupId>example.pde.rcp</groupId>
			<artifactId>example.rcp.app.ui</artifactId>
			<version>0.7.0-SNAPSHOT</version>
			<type>eclipse-plugin</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>example.pde.rcp</groupId>
			<artifactId>example.rcp.tests</artifactId>
			<version>${project.version}</version>
			<type>eclipse-test-plugin</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>example.pde.rcp</groupId>
			<artifactId>example.rcp.tests.it</artifactId>
			<version>${project.version}</version>
			<type>eclipse-test-plugin</type>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>