name: 10 build validatation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

#    - name: caching idefix / ~/.klibio
#      uses: actions/cache@v3
#      with:
#        path: |
#          ~/.ecdev
#          ~/.m2
#          ~/.p2
#        key: dev-${{ hashFiles('~/.klibio/klibio.sh') }}

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          8
          11
          17
          21

    - name: build
      shell: bash
      run: |
        echo -e "#\n# build\n#\n"
        echo "# configure environment for maven/tycho calls"
        export JAVA_HOME_8=$JAVA_HOME_8_X64
        export JAVA_HOME_11=$JAVA_HOME_11_X64
        export JAVA_HOME_17=$JAVA_HOME_17_X64
        export JAVA_HOME_21=$JAVA_HOME_21_X64
        export PATH=$JAVA_HOME/bin:$PATH
        ./build.sh --jar-signing
      continue-on-error: true
