name: build-validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: dev
    env:
      REPOSILITE_ID: ${{ vars.REPOSILITE_ID }}
      REPOSILITE_URL: ${{ vars.REPOSILITE_URL }}
      REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
      REPOSILITE_TOKEN: ${{ secrets.REPOSILITE_TOKEN }}
      APP_FEATURE_PRODUCT: 'example.rcp.app.ui.feature.product'
      APP_BUNDLE_PRODUCT: 'example.rcp.app.ui.plugin.product'
      APP_FEATURE: 'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
  
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: caching idefix / ~/.klibio
      uses: actions/cache@v3
      with:
        path: |
          ~/.ecdev
          ~/.m2
          ~/.p2
        key: dev-${{ hashFiles('~/.klibio/klibio.sh') }}

    - name: setup idefix
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/workflows/01-setup-global-properties.sh
        $GITHUB_WORKSPACE/.github/workflows/02-setup-idefix.sh
      continue-on-error: false
        
    - name: build
      shell: bash
      run: |
        echo -e "#\n# build\n#\n"
        echo "# configure environment for maven/tycho calls"
        #ls -laR ~/.klibio
        pushd ~/.klibio && set-java.sh 17 && popd
        $GITHUB_WORKSPACE/build.sh
      continue-on-error: false
