name: 20 snapshot deployment

on:
  push:
    branches: [ "next" ]
  workflow_dispatch:

jobs:
  snapshot:
    environment: dev
    env:
      REPOSILITE_ID: '${{ vars.REPOSILITE_ID }}'
      REPOSILITE_URL: '${{ vars.REPOSILITE_URL }}'
      REPOSILITE_USERNAME: '${{ secrets.REPOSILITE_USERNAME }}'
      REPOSILITE_TOKEN: '${{ secrets.REPOSILITE_TOKEN }}'
      APP_FEATURE_PRODUCT: 'example.rcp.app.ui.feature.product'
      APP_BUNDLE_PRODUCT: 'example.rcp.app.ui.plugin.product'
      APP_FEATURE: 'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
  
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

#    - name: caching idefix / ~/.klibio
#      uses: actions/cache@v3
#      with:
#        path: |
#          ~/.ecdev
#          ~/.m2
#          ~/.p2
#        key: dev-${{ hashFiles('~/.klibio/klibio.sh') }}

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          8
          11
          17
          21

    - name: build
      shell: bash
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        export PATH=$JAVA_HOME/bin:$PATH
        ./build.sh --jar-signing --deploy
      continue-on-error: true
     
    - name: Generate Changelog
      run: |
        env | sort > ${{ github.workspace }}-CHANGELOG.txt

    - name: Finding files
      run: |
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        FILELIST=$(find 'releng/repo.binary/target/repository' -print | sort)
        echo "FILELIST=$(echo $FILELIST)" >> $GITHUB_ENV

    - name: Debug
      run: |
        env | sort
    
    - name: Release
      uses: softprops/action-gh-release@v2
#      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ github.workspace }}-CHANGELOG.txt
            $FILELIST
          draft: true
          prerelease: false
