name: 20 snapshot deployment

on:
  push:
    branches: [ "next" ]
  workflow_dispatch:

jobs:
  snapshot:
    environment: dev
    env:
      REPOSILITE_ID: '${{ vars.REPOSILITE_ID }}'
      REPOSILITE_URL: '${{ vars.REPOSILITE_URL }}'
      REPOSILITE_USERNAME: '${{ secrets.REPOSILITE_USERNAME }}'
      REPOSILITE_TOKEN: '${{ secrets.REPOSILITE_TOKEN }}'
      APP_FEATURE_PRODUCT: 'example.rcp.app.ui.feature.product'
      APP_BUNDLE_PRODUCT: 'example.rcp.app.ui.plugin.product'
      APP_FEATURE: 'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
  
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

#    - name: caching idefix / ~/.klibio
#      uses: actions/cache@v3
#      with:
#        path: |
#          ~/.ecdev
#          ~/.m2
#          ~/.p2
#        key: dev-${{ hashFiles('~/.klibio/klibio.sh') }}

    - name: setup idefix
      shell: bash
      run: |
        rm -rf ~/.m2
        rm -rf ~/.p2
        .github/workflows/setup-idefix.sh
      continue-on-error: false

    - name: build
      shell: bash
      run: |
        ./build.sh --jar-signing --deploy
      continue-on-error: false
     
    - name: Generate Changelog
      run: |
        env | sort > ${{ github.workspace }}-CHANGELOG.txt

    - name: Finding files
      id: finding-files        
      run: |
        {
          ls -la .
          ls -la releng/repo.binary/target/repository
          echo 'FILELIST<<EOF'
          find 'releng/repo.binary/target/repository' -print 
          echo EOF
        } >> "$GITHUB_ENV"
    
    - name: Release
      uses: softprops/action-gh-release@v2
#      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ github.workspace }}-CHANGELOG.txt
            $FILELIST
          draft: true
          prerelease: false
