name: build-validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#on:
#  workflow_dispatch:
#    inputs:
#      name:
#        description: 'build-evaluation'
#        default: 'World'
#        required: true
#        type: string

jobs:
  build:
    environment: pekirsc
    env:
      ARTIFACTORY_ID: ${{ vars.ARTIFACTORY_ID }}
      ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      GIT_ID: ${{ vars.GIT_ID }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GIT_URL: ${{ vars.GIT_URL }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      APP_FEATURE_PRODUCT: 'example.rcp.app.ui.feature.product'
      APP_BUNDLE_PRODUCT: 'example.rcp.app.ui.plugin.product'
      APP_FEATURE: 'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
  
#    runs-on: [road-runner, large]
    runs-on: [road-runner, medium]

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: caching idefix / ~/.ecdev
      uses: actions/cache@v3
      with:
        path: |
          ~/.ecdev
          ~/.m2
          ~/.p2
        key: ecdev-${{ hashFiles('~/.ecdev/eclib.sh') }}

    - name: setup idefix
      shell: bash
      run: |
        #echo -e "#\n# debug - begin\n#\n"
        # ls -laR ~
        # ls -laR .
        #env | sort
        #echo -e "#\n# debug - end\n#\n"
        $GITHUB_WORKSPACE/.github/workflows/1-setup-ec-global-properties.sh
        $GITHUB_WORKSPACE/.github/workflows/2-gh-setup-idefix.sh
        ls ~/.*
      continue-on-error: false


    - name: build
      shell: bash
      run: |
        echo -e "#\n# debug env\n#\n"
        env | sort
        export JAVA_HOME=~/.ecdev/java/ee/JAVA17
        echo -e "#\n# build\n#\n"
        $GITHUB_WORKSPACE/build.sh
      continue-on-error: false

# does not work - https://github.com/actions/upload-artifact/issues/109      
#    - name: upload product ${{env.APP_FEATURE_PRODUCT}}-*-linux.gtk.aarch64.tar.gz
#      uses: actions/upload-artifact@v3
#      with:
#        name: single-file_${{env.APP_FEATURE_PRODUCT}}_linux.gtk.aarch64.tar.gz
#        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE_PRODUCT}}-*-linux.gtk.aarch64.tar.gz
#        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE_PRODUCT}}_linux.gtk.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE_PRODUCT}}_linux.gtk.aarch64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE}}/linux/gtk/aarch64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE_PRODUCT}}_linux.gtk.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE_PRODUCT}}_linux.gtk.x86_64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE}}/linux/gtk/x86_64
        if-no-files-found: error

    - name: upload product ${{env.APP_FEATURE_PRODUCT}}_macosx.cocoa.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE_PRODUCT}}_macosx.cocoa.aarch64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE}}/macosx/cocoa/aarch64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE_PRODUCT}}_macosx.cocoa.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE_PRODUCT}}_macosx.cocoa.x86_64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE}}/macosx/cocoa/x86_64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE_PRODUCT}}_win32.win32.x86_64.zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE_PRODUCT}}_win32.win32.x86_64.zip
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_FEATURE}}/win32/win32/x86_64
        if-no-files-found: error

    - name: upload product ${{env.APP_BUNDLE_PRODUCT}}_linux.gtk.aarch64.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE_PRODUCT}}_linux.gtk.aarch64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_BUNDLE}}/linux/gtk/aarch64
        if-no-files-found: error
      
    - name: upload product ${{env.APP_BUNDLE_PRODUCT}}_linux.gtk.x86_64.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE_PRODUCT}}_linux.gtk.x86_64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_BUNDLE}}/linux/gtk/x86_64
        if-no-files-found: error

    - name: upload product ${{env.APP_BUNDLE_PRODUCT}}_macosx.cocoa.aarch64.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE_PRODUCT}}_macosx.cocoa.aarch64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_BUNDLE}}/macosx/cocoa/aarch64
        if-no-files-found: error

    - name: upload product ${{env.APP_BUNDLE_PRODUCT}}_macosx.cocoa.x86_64.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE_PRODUCT}}_macosx.cocoa.x86_64.tar.gz
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_BUNDLE}}/macosx/cocoa/x86_64
        if-no-files-found: error

    - name: upload product ${{env.APP_BUNDLE_PRODUCT}}_win32.win32.x86_64.zip
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE_PRODUCT}}_win32.win32.x86_64.zip
        path: ${{ github.workspace }}/releng/products/target/products/${{env.APP_BUNDLE}}/win32/win32/x86_64
        if-no-files-found: error

    - name: upload repo.binary
      uses: actions/upload-artifact@v3
      with:
        name: repo.binary.zip
        path: ${{ github.workspace }}/releng/repo.binary/target/repository
        if-no-files-found: error

    - name: upload repo.sdk
      uses: actions/upload-artifact@v3
      with:
        name: repo.sdk.zip
        path: ${{ github.workspace }}/releng/repo.sdk/target/repository
        if-no-files-found: error
