name: snapshot deployment

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
on:
  workflow_dispatch:
#    inputs:
#      name:
#        description: 'build-evaluation'
#        default: 'World'
#        required: true
#        type: string

jobs:
  build:
    environment: pekirsc
    env:
      ARTIFACTORY_ID: ${{ vars.ARTIFACTORY_ID }}
      ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      GIT_ID: ${{ vars.GIT_ID }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GIT_URL: ${{ vars.GIT_URL }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      APP_FEATURE_PRODUCT: 'example.rcp.app.ui.feature.product'
      APP_BUNDLE_PRODUCT: 'example.rcp.app.ui.plugin.product'
      APP_FEATURE: 'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
  
#    runs-on: [road-runner, large]
    runs-on: [road-runner, medium]

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: caching idefix / ~/.ecdev
      uses: actions/cache@v3
      with:
        path: |
          ~/.ecdev
          ~/.m2
          ~/.p2
        key: ecdev-${{ hashFiles('~/.ecdev/eclib.sh') }}

    - name: setup idefix
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/workflows/1-setup-ec-global-properties.sh
        $GITHUB_WORKSPACE/.github/workflows/2-gh-setup-idefix.sh
      continue-on-error: false

    - name: build
      shell: bash
      run: |
        echo -e "#\n# build\n#\n"
        echo "# configure environment for maven/tycho calls"
        . ~/.ecdev/set-env.sh
        . ~/.ecdev/set-java.sh 17
        $GITHUB_WORKSPACE/build.sh --jar-signing --deploy
      continue-on-error: false
