name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#on:
#  workflow_dispatch:
#    inputs:
#      name:
#        description: 'build-evaluation'
#        default: 'World'
#        required: true
#        type: string

jobs:
  build:
    env:
      APP_FEATURE:  'example-rcp-app-ui-feature'
      APP_BUNDLE: 'example-rcp-app-ui-plugin'
    
    runs-on: [ self-hosted, linux, X64 ]

    steps:

    - name: debug-env
      shell: bash
      run: |
        echo -e "#\n# environment variables\n#\n#\n"
        env | sort

    - name: checkout
      uses: actions/checkout@v3

    - name: debug after checkout
      shell: bash
      run: |
        ls -laR ~
        ls -laR .

    - name: setup github env / idefix
      shell: bash
      run: |
        $GITHUB_WORKSPACE/.github/workflows/gh-setup-idefix.sh

    - name: build
      shell: bash
      run: |
        echo -e "#\n# debug env\n#\n"
        env | sort
        export JAVA_HOME=~/.klibio/java/ee/JAVA17
        echo -e "#\n#\ build\n#\n"
        $GITHUB_WORKSPACE/build.sh
 
    - name: upload product ${{env.APP_FEATURE}}_linux.gtk.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE}}_linux.gtk.aarch64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_FEATURE}}/linux/gtk/aarch64
        if-no-files-found: error

    - name: upload product ${{env.APP_BUNDLE}}_linux.gtk.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE}}_linux.gtk.aarch64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_BUNDLE}}/linux/gtk/aarch64
        if-no-files-found: error

    - name: upload product ${{env.APP_FEATURE}}_linux.gtk.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE}}_linux.gtk.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_FEATURE}}/linux/gtk/x86_64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_BUNDLE}}_linux.gtk.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE}}_linux.gtk.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_BUNDLE}}/linux/gtk/x86_64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE}}_macosx.cocoa.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE}}_macosx.cocoa.aarch64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_FEATURE}}/macosx/cocoa/aarch64
        if-no-files-found: error
    
    - name: upload product ${{env.APP_BUNDLE}}_macosx.cocoa.aarch64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE}}_macosx.cocoa.aarch64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_BUNDLE}}/macosx/cocoa/aarch64
        if-no-files-found: error

    - name: upload product ${{env.APP_FEATURE}}_macosx.cocoa.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE}}_macosx.cocoa.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_FEATURE}}/macosx/cocoa/x86_64
        if-no-files-found: error
      
    - name: upload product ${{env.APP_BUNDLE}}_macosx.cocoa.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE}}_macosx.cocoa.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_BUNDLE}}/macosx/cocoa/x86_64
        if-no-files-found: error
  
    - name: upload product ${{env.APP_FEATURE}}_win32.win32.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_FEATURE}}_win32.win32.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_FEATURE}}/win32/win32/x86_64
        if-no-files-found: error
        
    - name: upload product ${{env.APP_BUNDLE}}_win32.win32.x86_64
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.APP_BUNDLE}}_win32.win32.x86_64
        path: ${{ github.workspace }}/releng/example.rcp.products/target/products/${{env.APP_BUNDLE}}/win32/win32/x86_64
        if-no-files-found: error

    - name: upload p2 repository example.rcp.site
      uses: actions/upload-artifact@v3
      with:
        name: example.rcp.site
        path: ${{ github.workspace }}/releng/example.rcp.site/target/repository/*
        if-no-files-found: error

    - name: upload p2 repository example.rcp.site.source
      uses: actions/upload-artifact@v3
      with:
        name: example.rcp.site.source
        path: ${{ github.workspace }}/releng/example.rcp.site.source/target/repository/*
        if-no-files-found: error
